---
# Redis Configuration
redis_version: "6:8.2.0-1rl1~jammy1"  # Leave empty for latest, or specify version like "6:7.4.2-1rl1~jammy1"
redis_port: 6379
redis_bind_interface: "0.0.0.0"
redis_password: ""  # Set a strong password for production
redis_maxmemory: "4gb"
redis_maxmemory_policy: "allkeys-lru"

# Redis Directories
redis_dir: "/var/lib/redis"
redis_config_dir: "/etc/redis"
redis_config_dir_alt: "/opt/redis/conf"  # Alternative config directory
redis_log_dir: "/var/log/redis"
redis_pid_file: "/var/run/redis/redis-server.pid"

# Sentinel Configuration
sentinel_port: 26379
sentinel_quorum: 2
sentinel_down_after_milliseconds: 5000
sentinel_parallel_syncs: 1
sentinel_failover_timeout: 10000

# Master Configuration
redis_master_name: "mymaster"
redis_master_ip: "{{ hostvars[groups['redis_cluster'][0]]['ansible_default_ipv4']['address'] }}"

# System Configuration
redis_user: "redis"
redis_group: "redis"

# Security
redis_protected_mode: "yes"
redis_tcp_keepalive: 300

# Persistence
redis_save_config:
  - "900 1"   # Save if at least 1 key changed in 900 seconds
  - "300 10"  # Save if at least 10 keys changed in 300 seconds
  - "60 10000" # Save if at least 10000 keys changed in 60 seconds

redis_appendonly: "no"
redis_appendfsync: "everysec"
